#!/usr/bin/env python

# client name: comma
#
# This client script requires python 3.6 or higher. 
# If your system does not have websockets library installed, 
# please install it using pip: "pip install websockets"
#
# USAGE: download this script together with your private key to your server and start it there.
# When this script is active you will be able to start and stop a tunnel from your server to our access point
# through the web interface.
#
# Ensure that this script is automatically started upon reboot!
#
# Warning: on unix/linux based systems this script opens ssh tunnels with StrictHostKeyChecking=no option.
# It means they will automatically accept forwarding server signature and put it in known_hosts file. If you want
# to turn this option off read below how to do it. Please take note that if you turn this option off,
# the first time ssh tunnel is opening you will have to manually authorize to add the signature
# to known_hosts file
# On windows systems this option is disabled because plink.exe does not support it.
#
# There are 5 command line arguments
# * private_key_file - a full path of private key file (if not specified it is assumed
#       to be 'id_rsa' in local directory)
# * debug - if set it will write debugging information to logger
# * console - if set logging will also be sent to console
# * stricthostkeychecking - turn on StrictHostKeyChecking for ssh tunnel
# * dropbear - uses dropbear dbclient instead of ssh
#
# If dropbear client is used please note that you need to convert your private key file from RFC4716 to PEM format 
# using the following command: "dropbearconvert openssh dropbear id_rsa_RFC4716_FORMAT id_rsa_PEM_FORMAT"
#
# Examples:
# python sshreachme.py '/root/.ssh/my_private_key' debug console
#   this will use private key in '/root/.ssh/my_private_key' file and will write all debug messages
#   to console as well as to the log file
#
# python sshreachme.py console stricthostkeychecking
#   this will use private key in 'id_rsa' file in local directory, will write only error messages to
#   console and log file and will start ssh tunnel with StrictHostKeyChecking=yes switch
#
# python sshreachme.py
#   this will use private key in 'id_rsa' file in local directory, will write only error messages to
#   log file and will start ssh tunnel with StrictHostKeyChecking=no switch
#
# python sshreachme.py /temp/id_rsa dropbear
#   this will use private key from '/temp/id_rsa' file, will write only error messages to
#   log file and will use dropbear's dbclient instead of ssh. The id_rsa file must be in PEM format

import subprocess
import time
import os
import json
import signal
import sys
import logging
import platform
from logging.handlers import TimedRotatingFileHandler
from stat import *
from datetime import datetime
from urllib.parse import urlencode
import websockets
import asyncio

try:
    from shutil import which
except Exception as e:
    from distutils import spawn     # for python 2

try:
    from urllib2 import urlopen, URLError
except Exception as e:
    from urllib.request import urlopen, URLError     # for python 2

# these values are generated by sshreach.me and should not be changed
URL = 'wss://w1.sshreach.me:8444'
PORTS_ID = '23431'
UNIX_USERNAME = 'Qk8iPlkjo5Gx2DjBH1I0yqKC05wR3V'
HOST_UUID = 'e7086672-79ae-4a2c-8caf-8ee9c2868970'
USER_ID = '21182'
DB_SERVER_KEY = 'B9iuQ7HIXElzbhzrlNSR'

# this is the address to which your forwarded port should be forwarded to. This address should be changed only if
# the ssh connection and the server you want to connect to are not on the same machine.
ADDRESS = 'localhost'

# for windows users: change these two values to match your settings
PLINK_PATH = 'c:\\sshreachme'   #   the folder where your plink.exe is located
PLINK_EXECUTABLE = 'plink.exe'  #   the name of the plink executable

debug = False
console = False
StrictHostKeyChecking = False
dropbear = False
private_key = "id_rsa"
allow_multiple_instances = False

SCRIPT_VERSION = '612'

# check command line switches
for arg in sys.argv:
    if arg == "debug":
        debug = True
    elif arg == "console":
        console = True
    elif arg == "stricthostkeychecking":
        StrictHostKeyChecking = True
    elif arg == "dropbear":
        dropbear = True
    elif arg == "allowmultipleinstances":
        allow_multiple_instances = True
    elif arg != sys.argv[0]:
        private_key = arg

logger = logging.getLogger(__name__)

if debug:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.WARNING)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

logfile = os.path.join(os.path.dirname(os.path.realpath(__file__)), "sshreachme.log")
fileHandler = TimedRotatingFileHandler(logfile, when="D", interval=1, backupCount=5)
fileHandler.setFormatter(formatter)
if debug:
    fileHandler.setLevel(logging.DEBUG)
else:
    fileHandler.setLevel(logging.WARNING)
logger.addHandler(fileHandler)

if console:
    consoleHandler = logging.StreamHandler()
    consoleHandler.setFormatter(formatter)
    if debug:
        consoleHandler.setLevel(logging.DEBUG)
    else:
        consoleHandler.setLevel(logging.WARNING)
    logger.addHandler(consoleHandler)

WAITTIME = 5
SLEEPTIME = WAITTIME + 40

# check OS
logger.debug('Script version:{0}'.format(SCRIPT_VERSION))

if os.name == 'nt':
    logger.debug("running on windows, importing psutil")
    import psutil
elif os.name == 'posix':
    if platform.system() == 'Darwin':
        logger.debug("running on mac")
    else:
        logger.debug("running on linux")

logger.debug("python {0}".format(sys.version))

pidof_path = "pidof"
pgrep_path = "pgrep"

if os.name == 'posix':
    try:
        proc = subprocess.Popen(["whereis","pidof"], stdout=subprocess.PIPE)
        pidof_path = [s for s in proc.communicate()[0].decode("utf-8").split() if s[-6:] == "/pidof"][0]
        logger.debug("pidof_path:{0}".format(pidof_path))
    except Exception as e:
        pidof_path = "pidof"

    try:
        proc = subprocess.Popen(["whereis","pgrep"], stdout=subprocess.PIPE)
        pgrep_path = [s for s in proc.communicate()[0].decode("utf-8").split() if s[-6:] == "/pgrep"][0]
        logger.debug("pgrep_path:{0}".format(pgrep_path))
    except Exception as e:
        pgrep_path = "pgrep"

# We have to check if python executable exists. On rhel8 and centos8 "python" doesn't exist and self-restart is not possible
python_exists = True
if os.name == 'posix':
    try:
        if which("python") == None:
            python_exists = False
            logger.debug("Python executable doesn't exist, script auto-restart is not possible.")
    except Exception as e:
        # for python 2
        if spawn.find_executable("python") == None:
            python_exists = False
            logger.debug("Python executable doesn't exist, script auto-restart is not possible.")

# check ssh version

major_ssh_version = 0
opensshstring = ""
lastssherrormessage = ""

if dropbear == False:
    sshvers = subprocess.Popen(['ssh', '-V'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = sshvers.communicate()
    if len(stderr.split()) > 0 and len(stderr.split()[0]) > 8:
        if type(stderr.split()[0]) == str:
            opensshstring = stderr.split()[0]        
        else:
            opensshstring = "".join(map(chr, stderr.split()[0]))        

        try:
            if os.name == 'nt':
                if opensshstring[:20] == 'OpenSSH_for_Windows_':
                    major_ssh_version = int(opensshstring[20:21])
            else:
                if opensshstring[:8] == 'OpenSSH_':
                    major_ssh_version = int(opensshstring[8:9])
        except Exception as e:
            logger.debug("can not detect ssh version, opensshstring:{0}".format(opensshstring))            

def startSSH(data, private_key):
    global lastssherrormessage
    try:
        if os.name == 'posix':       # if os is linux or mac
            # first check if there is already started ssh
            pid = get_pid(data['iport'], data['forwarding_server'], private_key)
            if pid:
                logger.debug("ssh already active, pid:{0}".format(pid))
                return pid
            else:
                sshrsaoption = ""
                if dropbear == False and major_ssh_version >= 8:
                    sshrsaoption = "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"

                if dropbear == True:
                    if StrictHostKeyChecking:
                        # The line below should not be changed. If the dbclient command is changed then the corresponding line in get_pid() must
                        # also be changed otherwise the script might not recognize that dbclient connection is active and will try to open it
                        # again and again resulting in hundreds of inactive dbclient processes.
                        process = 'dbclient -N -i {0} -R {1}:{4}:22 {3}@{2} &'.format(private_key,
                            data['iport'], data['forwarding_server'], UNIX_USERNAME, ADDRESS)
                    else:
                        # The line below should not be changed. If the dbclient command is changed then the corresponding line in get_pid() must
                        # also be changed otherwise the script might not recognize that dbclient connection is active and will try to open it
                        # again and again resulting in hundreds of inactive dbclient processes.
                        process = 'dbclient -y -N -i {0} -R {1}:{4}:22 {3}@{2} &'.format(private_key,
                            data['iport'], data['forwarding_server'], UNIX_USERNAME, ADDRESS)
                else:
                    if StrictHostKeyChecking:
                        # The line below should not be changed. If the ssh command is changed then the corresponding line in get_pid() must
                        # also be changed otherwise the script might not recognize that ssh connection is active and will try to open it
                        # again and again resulting in hundreds of inactive ssh processes.
                        process = 'ssh {5} -N -i {0} -R {1}:{4}:22 {3}@{2} &'.format(private_key,
                            data['iport'], data['forwarding_server'], UNIX_USERNAME, ADDRESS, sshrsaoption)
                    else:
                        # The line below should not be changed. If the ssh command is changed then the corresponding line in get_pid() must
                        # also be changed otherwise the script might not recognize that ssh connection is active and will try to open it
                        # again and again resulting in hundreds of inactive ssh processes.
                        process = 'ssh -o StrictHostKeyChecking=no {5} -o LogLevel=ERROR -N -i {0} -R {1}:{4}:22 {3}@{2} &'.format(private_key,
                            data['iport'], data['forwarding_server'], UNIX_USERNAME, ADDRESS, sshrsaoption)

                logger.debug("Starting ssh:{0}".format(process))

                proc = subprocess.Popen(process, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                time.sleep(3)
                # surround communicate with try/except block to catch timeout
                try:
                    out, err = proc.communicate(timeout = 5)
                    if err:
                        logger.debug (err)
                        lastssherrormessage = err
                except Exception as e:
                    logger.debug("ssh error message:{0}".format(e))
                    pass

                return get_pid(data['iport'], data['forwarding_server'], private_key)
        elif os.name == 'nt':   # os is windows
            process = '{5} -N -batch -i {0} -R {1}:{4}:22 {3}@{2} &'.format(private_key,
                data['iport'], data['forwarding_server'],  UNIX_USERNAME, ADDRESS,
                os.path.join(PLINK_PATH, PLINK_EXECUTABLE))

            logger.debug("Starting plink:{0}".format(process))
            proc = subprocess.Popen(process, shell=True)
            time.sleep(3)
            return get_pid(data['iport'], data['forwarding_server'], private_key)
    except Exception as e:
        logger.debug(e)
        return 0

def get_pid(iport, forwarding_server, private_key):
    # get pids of all ssh processes
    if os.name == 'posix':
        try:
            # get pids of all ssh processes
            if dropbear == True:
                proc = subprocess.Popen([pidof_path,"dbclient"], stdout=subprocess.PIPE)
            else:
                proc = subprocess.Popen([pidof_path,"ssh"], stdout=subprocess.PIPE)

            pids = map(int, (proc.communicate()[0].decode("utf-8")).split())

            for pid in pids:
                cmdline = open(os.path.join('/proc', str(pid), 'cmdline'), 'rb').read().strip()

                if '-N' in str(cmdline) and '-R' in str(cmdline) and "{0}:{1}:22".format(iport, ADDRESS) in str(cmdline) and "{1}@{0}".format(forwarding_server, UNIX_USERNAME) in str(cmdline):
                    return pid

            return 0
        except Exception as e:
            # we don't have pidof or /proc, try ps-ing
            sshrsaoption = ""
            if dropbear == False and major_ssh_version >= 8:
                sshrsaoption = "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa"

            if dropbear == True:
                if StrictHostKeyChecking:
                    # The line below should not be changed. If the dbclient command is changed then the corresponding line in startSSH() must
                    # also be changed otherwise the script might not recognize that dbclient connection is active and will try to open it
                    # again and again resulting in hundreds of inactive dbclient processes.
                    checkline = 'dbclient -N -i {0} -R {1}:{4}:22 {3}@{2}'.format(private_key, 
                        iport, forwarding_server, UNIX_USERNAME, ADDRESS)
                else:
                    # The line below should not be changed. If the dbclient command is changed then the corresponding line in startSSH() must
                    # also be changed otherwise the script might not recognize that dbclient connection is active and will try to open it
                    # again and again resulting in hundreds of inactive dbclient processes.
                    checkline = 'dbclient -y -N -i {0} -R {1}:{4}:22 {3}@{2}'.format(private_key, 
                        iport, forwarding_server, UNIX_USERNAME, ADDRESS)
            else:
                if StrictHostKeyChecking:
                    # The line below should not be changed. If the ssh command is changed then the corresponding line in startSSH() must
                    # also be changed otherwise the script might not recognize that ssh connection is active and will try to open it
                    # again and again resulting in hundreds of inactive ssh processes.
                    checkline = 'ssh {5} -N -i {0} -R {1}:{4}:22 {3}@{2}'.format(private_key, 
                        iport, forwarding_server, UNIX_USERNAME, ADDRESS, sshrsaoption)
                else:
                    # The line below should not be changed. If the ssh command is changed then the corresponding line in startSSH() must
                    # also be changed otherwise the script might not recognize that ssh connection is active and will try to open it
                    # again and again resulting in hundreds of inactive ssh processes.
                    checkline = 'ssh -o StrictHostKeyChecking=no {5} -o LogLevel=ERROR -N -i {0} -R {1}:{4}:22 {3}@{2}'.format(private_key, 
                        iport, forwarding_server, UNIX_USERNAME, ADDRESS, sshrsaoption)

            proc = subprocess.Popen(["ps", "-ax"], stdout=subprocess.PIPE)

            pss = proc.communicate()[0].decode("utf-8").split("\n")
            for ps in pss:
                if checkline in ps:
                    ids = ps.split()
                    return int(ids[0])
            return 0
    elif os.name == 'nt':
        for p in psutil.process_iter():
            if p.name() == PLINK_EXECUTABLE:
                if '{0}:{1}:22'.format(iport, ADDRESS) in p.cmdline() and '{0}@{1}'.format(UNIX_USERNAME, forwarding_server) in p.cmdline():
                    return int(p.pid)
        return 0

def is_process_active(pid, iport, forwarding_server):
    if os.name == 'posix':
        try:
            os.kill(pid, 0)
            return True
        except:
            return False
    elif os.name == 'nt':
        for p in psutil.process_iter():
            if p.name() == PLINK_EXECUTABLE:
                if '{0}:{1}:22'.format(iport, ADDRESS) in p.cmdline() and '{0}@{1}'.format(UNIX_USERNAME, forwarding_server) in p.cmdline():
                    return True
        return False

async def looper(private_key):
    pid = 0
    retries = 5
    timeouterrors = 0
    urlunreachableerrors = 0
    last_good_ping_time = datetime.now()
    disconnect_ssl_when_server_unreachable = False
    lasttime = time.time()
    upgradable = False
    response = ""

    try:
        async with websockets.connect(URL) as ws:
            while True:
                try:
                    # check if connection needs to be made
                    response = ""
                    clientrequest = {"ports_id":PORTS_ID, "host_uuid":HOST_UUID, "user_id":USER_ID, 
                        "db_server_key":DB_SERVER_KEY, "script_version":SCRIPT_VERSION, "upgradable":upgradable}

                    try:
                        await ws.send(json.dumps(clientrequest))
                    except websockets.exceptions.ConnectionClosed:
                        logger.error("ConnectionClosed exception. Cannot send request.")
                        return

                    try:
                        response = await ws.recv()
                    except websockets.exceptions.ConnectionClosed:
                        logger.error("ConnectionClosed exception. Cannot receive response.")
                        return
                    data = json.loads(response)

                    timeouterrors = 0

                    if len(data) > 0:
                        if 'error' in data:
                            if "Client not found" in data['error'] or "bad key" in data['error']:
                                logger.error('Client not found, exiting')
                                sys.exit()
                            else:
                                raise Exception(data['error'])
                        else:
                            last_good_ping_time = datetime.now()
                            disconnect_ssl_when_server_unreachable = data['disconnect_ssl_when_server_unreachable'] == 'T'
                            if 'command' in data:
                                urlunreachableerrors = 0

                                logger.debug('Command:{0}'.format(data['command']))

                                #   activate the tunnel
                                if data['command'] == "1":
                                    if pid == 0 or (pid != 0 and is_process_active(pid, data['iport'], data['forwarding_server']) == False):
                                        logger.debug('ssh is inactive, starting ssh')
                                        #   we have received 'connect' signal, starting ssh tunnel
                                        pid = startSSH(data, private_key)
                                        logger.debug("Pid:{0}".format(pid))

                                        if pid != 0 and is_process_active(pid, data['iport'], data['forwarding_server']) == False:
                                            # ssh is not active, try again
                                            pid = startSSH(data, private_key)
                                            logger.debug("Pid2:{0}".format(pid))
                                        elif pid == 0:
                                            logger.debug("ssh not started, pid:{0}".format(pid))
                                            if retries == 0:
                                                logger.debug("can not start ssh, sending error message")
                                                retries = 5
                
                                                if isinstance(lastssherrormessage, (bytes, bytearray)):
                                                    strerrormsg = lastssherrormessage.decode('utf-8')
                                                else:
                                                    strerrormsg = lastssherrormessage

                                                error_data = {
                                                    "ports_id" : PORTS_ID,
                                                    "host_uuid" : HOST_UUID,
                                                    "user_id" : USER_ID,
                                                    "db_server_key" : DB_SERVER_KEY,
                                                    "error_message" : strerrormsg
                                                }

                                                try:
                                                    logger.debug("Sending ssh error message: {0}".format(error_data))
                                                    await ws.send(json.dumps(error_data))
                                                except websockets.exceptions.ConnectionClosed:
                                                    logger.error("ConnectionClosed exception. Cannot send request.")
                                                    return

                                                try:
                                                    response = await ws.recv()
                                                except websockets.exceptions.ConnectionClosed:
                                                    logger.error("ConnectionClosed exception. Cannot receive response.")
                                                    return
                                                data = json.loads(response)
                                            else:
                                                retries = retries - 1
                                                logger.debug("retries:{0}".format(retries))
                                        else:
                                            logger.debug("ssh started, pid:{0}".format(pid))
                                elif data['command'] == "0":
                                    retries = 5
                                    if pid == 0:
                                        pid = get_pid(data['iport'], data['forwarding_server'], private_key)
                                        logger.debug("Found pid:{0}".format(pid))
                                    if pid:
                                        try:
                                            logger.debug("Killing ssh, pid:{0}".format(pid))
                                            os.kill(pid, signal.SIGTERM)
                                            pid = 0
                                        except Exception as e:
                                            logger.warning(e)
                                            pid = 0
                            elif 'error' in data:
                                logger.error(data['error'])

                    else:
                        logger.error("bad response from server")

                    time.sleep(WAITTIME)  # do not change this value

                    # this is a very primitive way of testing for wakeup event but it works on every system
                    # without installing additional modules
                    now = time.time()
                    # check if computer was suspended
                    if (now - lasttime) > SLEEPTIME:
                        logger.debug("wake up detected")
                        #   we just woke up, check if tunnel is active
                        if pid != 0:
                            logger.info("tunnel was active during sleep - closing it")
                            #   tunnel is active but it is broken, close the tunnel and 
                            #   the new one will be opened if necessary 
                            os.kill(pid, signal.SIGTERM)
                            pid = 0
                        
                    lasttime = now

                except Exception as e:
                    # oops, for some reason we can't open url            
                    logger.error("{0}: {1}".format(type(e).__name__, e))
                    logger.error("clientrequest: {0}".format(clientrequest))
                    logger.error("response: {0}".format(response))

                    if isinstance(e, URLError):
                        if python_exists == True:
                            if timeouterrors == 3:
                                timeouterrors = 0
                                # restart this script only if execute bit is set
                                if os.access(__file__, os.X_OK):
                                    logger.error("Too many URLErrors. Client will now self restart.")
                                    os.execv(__file__, sys.argv)
                                    sys.exit()
                            else:
                                timeouterrors += 1

                    if python_exists == True:
                        if (datetime.now() - last_good_ping_time).seconds / 3600 >= 3: 
                           # last ping time was more than 3 hours ago

                            # restart this script only if execute bit is set
                            if os.access(__file__, os.X_OK):
                                logger.error("Last ping was more than 3 hours ago. Client will now self restart.")                    
                                os.execv(__file__, sys.argv)
                                sys.exit()

                    logger.error(e)
                    if urlunreachableerrors == 6:
                        urlunreachableerrors = 0
                        if disconnect_ssl_when_server_unreachable and pid != 0:
                            logger.debug("Killing ssh, pid:{0}".format(pid))
                            os.kill(pid, signal.SIGTERM)
                            pid = 0
                    else:
                        urlunreachableerrors += 1

                    time.sleep(WAITTIME)
    except Exception as e:
        logger.error("Exception in looper: {0}".format(e))
        return

def run_single_instance():
    if allow_multiple_instances == False:
        # check if another instance of this script is already running
        if os.name == 'posix':
            proc = subprocess.Popen([pgrep_path, "-f", os.path.basename(__file__)], stdout=subprocess.PIPE)
            pids = map(int, (proc.communicate()[0].decode("utf-8")).split())

            if len(list(pids)) > 1:
                logger.error("Another instance of sshreachme is already running. Exiting...")
                sys.exit()
        elif os.name == 'nt':
            procs = [p for p in psutil.process_iter() if 'python' in p.name() and os.path.basename(__file__) in p.cmdline()]

            if(len(procs) > 1):
                logger.error("Another instance of sshreachme is already running. Exiting...")
                sys.exit()

if __name__ == "__main__":
    run_single_instance()
    # check if private_key exists
    if os.path.isfile(private_key):
        if os.name == 'posix':
            #   check private_key's stat
            if oct(os.stat(private_key)[ST_MODE])[-3:] != '600':
                os.chmod(private_key, 0o600)
            #   Set the execute bit for this script if it is not set
            if not os.access(__file__, os.X_OK):
                os.chmod(__file__, 0o700)            

            while True:
                asyncio.get_event_loop().run_until_complete(looper(private_key))
                logger.info("Reconnecting...")
                time.sleep(4)
    else:
        logger.error("private key file not found: {0}".format(private_key))


