Import('env', 'envCython', 'arch')

common_libs = [
  'swaglog.cc',
  'util.cc',
  'watchdog.cc',
  'ratekeeper.cc'
]

params_obj = 'params.cc'
if arch == "larch64":
  # params.cc pulls in the full key registry and can exceed tici memory when
  # clang optimizes it with debug info enabled. Build that one translation unit
  # with lighter flags so on-device rebuilds stay reliable.
  params_env = env.Clone()
  for flag in ("-g", "-O2"):
    if flag in params_env["CCFLAGS"]:
      params_env["CCFLAGS"].remove(flag)
  params_env["CCFLAGS"] += ["-g0", "-O0"]
  params_obj = params_env.Object('params.cc')

common_libs.insert(0, params_obj)

_common = env.Library('common', common_libs, LIBS="json11")

files = [
  'clutil.cc',
]

_gpucommon = env.Library('gpucommon', files)
Export('_common', '_gpucommon')

if GetOption('extras'):
  env.Program('tests/test_common',
              ['tests/test_runner.cc', 'tests/test_params.cc', 'tests/test_util.cc', 'tests/test_swaglog.cc'],
              LIBS=[_common, 'json11', 'zmq', 'pthread'])

# Cython bindings
params_python = envCython.Program('params_pyx.so', 'params_pyx.pyx', LIBS=envCython['LIBS'] + [_common, 'zmq', 'json11'])

SConscript([
  'transformations/SConscript',
])

Import('transformations_python')
common_python = [params_python, transformations_python]

Export('common_python')
