import glob
import json
import os
import subprocess
import sys

from SCons.Script import Value

from openpilot.common.file_chunker import chunk_file, get_chunk_targets, get_existing_chunks
from openpilot.common.transformations.camera import _ar_ox_fisheye, _os_fisheye
from openpilot.common.transformations.model import DM_INPUT_SIZE, MEDMODEL_INPUT_SIZE
from openpilot.selfdrive.modeld.constants import ModelConstants
from openpilot.selfdrive.modeld.helpers import TG_INPUT_DEVICES_PATH, modeld_pkl_path, usbgpu_present

Import('env', 'envCython', 'arch', 'cereal', 'messaging', 'common', 'gpucommon', 'visionipc', 'transformations')
lenv = env.Clone()
lenvCython = envCython.Clone()

libs = [cereal, messaging, visionipc, gpucommon, common, 'capnp', 'kj', 'pthread']
frameworks = []

common_src = [
  "models/commonmodel.cc",
  "transforms/loadyuv.cc",
  "transforms/transform.cc",
]

CAMERA_CONFIGS = [
  (_ar_ox_fisheye.width, _ar_ox_fisheye.height),  # tici: 1928x1208
  (_os_fisheye.width, _os_fisheye.height),        # mici: 1344x760
]

# OpenCL is a framework on Mac
if arch == "Darwin":
  frameworks += ['OpenCL']
else:
  libs += ['OpenCL']

# Set path definitions
for pathdef, fn in {'TRANSFORM': 'transforms/transform.cl', 'LOADYUV': 'transforms/loadyuv.cl'}.items():
  for xenv in (lenv, lenvCython):
    xenv['CXXFLAGS'].append(f'-D{pathdef}_PATH=\\"{File(fn).abspath}\\"')

# Compile cython for the existing driver monitoring model path.
cython_libs = envCython["LIBS"] + libs
commonmodel_lib = lenv.Library('commonmodel', common_src)
lenvCython.Program('models/commonmodel_pyx.so', 'models/commonmodel_pyx.pyx', LIBS=[commonmodel_lib, *cython_libs], FRAMEWORKS=frameworks)

tinygrad_root = env.Dir("#").abspath
tinygrad_files = ["#" + x for x in glob.glob(env.Dir("#tinygrad_repo").relpath + "/**", recursive=True, root_dir=tinygrad_root)
                  if 'pycache' not in x and os.path.isfile(os.path.join(tinygrad_root, x))]


def estimate_pickle_max_size(onnx_size):
  return 1.2 * onnx_size + 10 * 1024 * 1024  # 20% + 10MB is plenty


def probe_devices():
  result = subprocess.run(
    [sys.executable, '-c', 'from tinygrad import Device\nprint("\\n".join(Device.get_available_devices()))'],
    cwd=tinygrad_root,
    capture_output=True,
    text=True,
    check=True,
  )
  return set(result.stdout.strip().splitlines())


available = probe_devices()
if 'CUDA' in available:
  tg_backend = 'CUDA'
  tg_flags = f'DEV={tg_backend}'
elif 'QCOM' in available:
  tg_backend = 'QCOM'
  tg_flags = f'DEV={tg_backend} IMAGE=1 FLOAT16=1 NOLOCALS=1 JIT_BATCH_SIZE=0 OPENPILOT_HACKS=1'
else:
  tg_backend = 'CPU'
  tg_flags = 'DEV=CPU' if arch == 'Darwin' else 'DEV=CPU:LLVM'

dmonitoring_model_tg_flags = {
  'larch64': 'DEV=QCOM FLOAT16=1 NOLOCALS=1 IMAGE=2 JIT_BATCH_SIZE=0',
  'Darwin': f'DEV=CPU HOME={os.path.expanduser("~")}',
}.get(arch, 'DEV=CPU CPU_LLVM=1')

tg_devices = {
  'selfdrive.modeld.modeld': {
    'default': {'WARP_DEV': tg_backend, 'QUEUE_DEV': tg_backend},
  },
  'selfdrive.modeld.dmonitoringmodeld': {
    'default': {'DEV': tg_backend},
  },
}

USBGPU = usbgpu_present()
if USBGPU:
  tg_devices['selfdrive.modeld.modeld']['usbgpu'] = {'WARP_DEV': tg_backend, 'QUEUE_DEV': 'AMD'}
  usbgpu_tg_flags = f'DEBUG=2 DEV=USB+AMD:LLVM WARP_DEV={tg_backend} FLOAT16=1 JIT_BATCH_SIZE=0 GMMU=0'
  usbgpu_lock = File("models/.usb_gpu.lock").abspath


def write_tg_devices(target, source, env):
  with open(str(target[0]), "w") as f:
    json.dump(tg_devices, f)
    f.write("\n")


tg_devices_node = lenv.Command(
  str(TG_INPUT_DEVICES_PATH),
  [Value(tg_devices)],
  write_tg_devices,
)

# tinygrad calls brew which needs a $HOME in the env
mac_brew_string = f'HOME={os.path.expanduser("~")}' if arch == 'Darwin' else ''
pythonpath_string = 'PYTHONPATH="${PYTHONPATH}:' + env.Dir("#tinygrad_repo").abspath + '"'

modeld_dir = Dir("#selfdrive/modeld").abspath
compile_modeld_script = [File(f"{modeld_dir}/compile_modeld.py")]
chunker_file = File("#common/file_chunker.py")

# Compile the split driving model into one tinygrad JIT bundle.
model_w, model_h = MEDMODEL_INPUT_SIZE
frame_skip = ModelConstants.MODEL_RUN_FREQ // ModelConstants.MODEL_CONTEXT_FREQ
driving_model_names = ['driving_vision', 'driving_off_policy', 'driving_on_policy']
camera_res_args = ' '.join(f'{cw}x{ch}' for cw, ch in CAMERA_CONFIGS)

for usbgpu in [False, True] if USBGPU else [False]:
  target_pkl_path = File(str(modeld_pkl_path(usbgpu))).abspath
  cmd_flags = usbgpu_tg_flags if usbgpu else tg_flags
  driving_onnx_deps = [p for m in driving_model_names
                       for p in get_existing_chunks(File(f"models/{m}.onnx").abspath)]
  cmd = (f'{pythonpath_string} {cmd_flags} {mac_brew_string} python3 {modeld_dir}/compile_modeld.py '
         f'--model-size {model_w}x{model_h} '
         f'--camera-resolutions {camera_res_args} '
         f'--vision-onnx {File("models/driving_vision.onnx").abspath} '
         f'--off-policy-onnx {File("models/driving_off_policy.onnx").abspath} '
         f'--on-policy-onnx {File("models/driving_on_policy.onnx").abspath} '
         f'--output {target_pkl_path} --frame-skip {frame_skip}')
  onnx_sizes_sum = sum(os.path.getsize(f) for f in driving_onnx_deps)
  chunk_targets = get_chunk_targets(target_pkl_path, estimate_pickle_max_size(onnx_sizes_sum))

  def do_chunk(target, source, env, pkl=target_pkl_path, chunks=chunk_targets):
    chunk_file(pkl, chunks)

  node = lenv.Command(
    chunk_targets,
    tinygrad_files + compile_modeld_script + driving_onnx_deps + [Value(camera_res_args), chunker_file, tg_devices_node],
    [cmd, do_chunk],
  )
  if usbgpu:
    lenv.SideEffect(usbgpu_lock, node)

# Compile driver monitoring model and tinygrad camera warps.
dmonitoring_fn = File("models/dmonitoring_model").abspath
dmonitoring_metadata_script = [File(Dir("#selfdrive/modeld").File("get_model_metadata.py").abspath)]
dmonitoring_metadata_cmd = f'{pythonpath_string} {dmonitoring_model_tg_flags} {mac_brew_string} python3 {modeld_dir}/get_model_metadata.py {dmonitoring_fn}.onnx'
lenv.Command(dmonitoring_fn + "_metadata.pkl", [dmonitoring_fn + ".onnx"] + tinygrad_files + dmonitoring_metadata_script + [tg_devices_node], dmonitoring_metadata_cmd)

dm_w, dm_h = DM_INPUT_SIZE
compile_dm_warp_script = [File(f"{modeld_dir}/compile_dm_warp.py")]
for cam_w, cam_h in CAMERA_CONFIGS:
  dm_pkl_path = File(f"models/dm_warp_{cam_w}x{cam_h}_tinygrad.pkl").abspath
  cmd = (f'{pythonpath_string} {tg_flags} {mac_brew_string} python3 {modeld_dir}/compile_dm_warp.py '
         f'--camera-resolution {cam_w}x{cam_h} --warp-to {dm_w}x{dm_h} '
         f'--output {dm_pkl_path}')
  lenv.Command(dm_pkl_path, tinygrad_files + compile_dm_warp_script + compile_modeld_script + [tg_devices_node], cmd)


def tg_compile(flags, model_name):
  fn = File(f"models/{model_name}").abspath
  return lenv.Command(
    fn + "_tinygrad.pkl",
    [fn + ".onnx"] + tinygrad_files + [tg_devices_node],
    f'{pythonpath_string} {flags} python3 {Dir("#tinygrad_repo").abspath}/examples/openpilot/compile3.py {fn}.onnx {fn}_tinygrad.pkl'
  )


tg_compile(dmonitoring_model_tg_flags, 'dmonitoring_model')
